# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-17 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20180116_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='publish_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='myblog',
            name='slug',
            field=models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='myblog',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='mymodel_images'),
        ),
    ]
