# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-25 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20180117_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostnew',
            name='blog',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.MyBlog'),
        ),
    ]
