# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-26 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20180127_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='avatar',
            field=models.ImageField(default='uploads\\gallery\\Tokyo, Japan.jpg', upload_to='uploads'),
        ),
    ]
