# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-26 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20180127_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='avatar',
            field=models.ImageField(default='uploads\\gallery\\Berlin, Germany.jpg', upload_to='uploads/'),
        ),
    ]
