# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-27 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20180127_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='avatar',
            field=models.ImageField(blank=True, default='uploads\\gallery\\Berlin, Germany.jpg', upload_to='uploads/'),
        ),
    ]
