# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-27 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20180127_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myblog',
            options={'permissions': (('view_myblog', 'View myblog'),), 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
    ]
